/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc_robot_subsystems_RobotNative_Native */

#ifndef _Included_frc_robot_subsystems_RobotNative_Native
#define _Included_frc_robot_subsystems_RobotNative_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc_robot_subsystems_RobotNative_Native
 * Method:    initialize
 * Signature: (Lfrc/robot/subsystems/RobotNative/InitInfo;)J
 */
JNIEXPORT jlong JNICALL Java_frc_robot_subsystems_RobotNative_00024Native_initialize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     frc_robot_subsystems_RobotNative_Native
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_frc_robot_subsystems_RobotNative_00024Native_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     frc_robot_subsystems_RobotNative_Native
 * Method:    submitLauncherControlRequest
 * Signature: (JLfrc/robot/subsystems/RobotNative/LauncherSubsystem/LauncherControlRequest;)V
 */
JNIEXPORT void JNICALL Java_frc_robot_subsystems_RobotNative_00024Native_submitLauncherControlRequest
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
